var data= [
  {
      "university": "銘傳大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 805,
      "local_student": 260,
      "intern_student": "",
      "english_course": 14,
      "international_point": "1. 全台最多國際學生\n2.設立全英語國際學院，台灣唯一在海外設立分校\n3. 伙伴（buddy）制度：為每名外籍生搭配一名台灣學生伙伴，協助適應在台生活及語言交換",
      "more": ""
  },
  {
      "university": "國立台灣大學",
      "cross_course": "Y",
      "short_term": "Y",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 793,
      "local_student": 1114,
      "intern_student": 6,
      "english_course": 2,
      "international_point": "1. 課程創新，如台大創新設計學院、國際教學聯盟（ipodia alliance）\n2. 與UIUC、澳洲雪梨大學、東京大學、京都大學、德國漢堡大學等校級學術合作\n3. 與日本筑波大學、法國波爾多大學三聯學位\n4. 海外特色實習計劃：琉球大學「日本企業實習計劃」、華盛頓實習與學術研討中心、加州大學爾灣分校",
      "more": "設計思考解決全球問題：\n台大設計學院"
  },
  {
      "university": "國立成功大學",
      "cross_course": "Y",
      "short_term": "Y",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 753,
      "local_student": 474,
      "intern_student": 7,
      "english_course": 9,
      "international_point": "1.「臥虎．藏龍」計劃：招募國外年輕人來台上課跟實習\n2. 美國亞利桑那大學Ｘ台灣綜合大學企業實習營隊\n3. 國際有薪與學分實習計劃\n4. 國際產學聯盟計劃\n5.「踏溯台南」0學分通識課：從周遭的文化與歷史出發",
      "more": ""
  },
  {
      "university": "義守大學",
      "cross_course": "Y",
      "short_term": "N",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 686,
      "local_student": 285,
      "intern_student": "",
      "english_course": 6,
      "international_point": "1. 國際學生比例排名全國前三\n2. 參與歐盟Erasmus+ 保加利亞斯維什托夫經濟學院交換\n3. 「學士後醫學系外國學生專班」：培育邦交國的醫療人才\n4. 全台第一個跟香港理工大學簽訂學士雙學位計劃\n5. 義守大學管理學院雙聯學位",
      "more": ""
  },
  {
      "university": "國立台灣科技大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 620,
      "local_student": 270,
      "intern_student": 3,
      "english_course": 37,
      "international_point": "1. 全台國際學生比例最高",
      "more": ""
  },
  {
      "university": "國立台灣師範大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 558,
      "local_student": 372,
      "intern_student": 2,
      "english_course": 2,
      "international_point": "1. 華語教學為主要特色\n2. 提供補助金讓學生出國實習、交換",
      "more": ""
  },
  {
      "university": "國立政治大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 534,
      "local_student": 1018,
      "intern_student": "",
      "english_course": 8,
      "international_point": "1. 108年推動全英語的國際學院，從行政到教學都是英語。國際學院主打亞太商務專業，預計與國外頂尖大學師資合作開課，課程包括數位電商、華語、國際關係、國際傳播\n2. 鼓勵學生交換時，同時長期實習\n3. 提供超過400門全英語授課課程\n4. 全台第一個東南亞研究中心，設立東南亞語言與文化學士學位學程\n5. 傳播學院與日本明治大學、泰國朱拉隆功大學合辦「想像亞洲」國際創作工作坊",
      "more": ""
  },
  {
      "university": "國立交通大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "Y",
      "internalize": "",
      "fori_student": 517,
      "local_student": 505,
      "intern_student": 3,
      "english_course": 7,
      "international_point": "1. 台灣聯合大學系統海外實習",
      "more": ""
  },
  {
      "university": "逢甲大學",
      "cross_course": "Y",
      "short_term": "Y",
      "internship": "N",
      "internalize": "N",
      "fori_student": 497,
      "local_student": 734,
      "intern_student": 8,
      "english_course": 4,
      "international_point": "1. 與上海同濟大學、香港理工大學、世新大學及澳門科技大學共同舉辦兩岸四地五校「暑期聯合大學」\n2. 國際科技與管理學院：和國外三校（美國普渡大學、美國聖荷西州立大學、澳洲皇家墨爾本理工大學）合作，開設2+2學制國際專班",
      "more": ""
  },
  {
      "university": "淡江大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 475,
      "local_student": 1080,
      "intern_student": 1,
      "english_course": 10,
      "international_point": "1. 在地國際化，舉辦Asian community leadership seminar，探討國際間共同的社會議題\n2. 俄文系與俄羅斯大學生遠距交流",
      "more": "國際遠距課程：淡江大學俄語系"
  },
  {
      "university": "國立清華大學",
      "cross_course": "Y",
      "short_term": "Y",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 457,
      "local_student": 345,
      "intern_student": 3,
      "english_course": 9,
      "international_point": "1. 台灣聯合大學系統海外實習\n2. TIX以色列創業實習計劃\n3. 利物浦大學雙聯學位\n4. 利用台灣高科技半導體優勢，和工研院、印度理工大學三邊合作",
      "more": "國際創業：清大以色列創業計劃"
  },
  {
      "university": "國立中央大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 425,
      "local_student": 350,
      "intern_student": "",
      "english_course": 3,
      "international_point": "1. 台灣聯合大學系統海外實習\n2. 「新南向計劃」經費，送學生至孟加拉及尼泊爾進行「商管及社會科學」領域國際實習交流，由該校尤努斯社會企業中心與其他國家社會企業合作，出發前要求學生參與在地企業實習，提高學生對於全球議題的關注",
      "more": ""
  },
  {
      "university": "中國文化大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 330,
      "local_student": 386,
      "intern_student": 2,
      "english_course": 2,
      "international_point": "1. 舉辦暑期兩岸青年領袖交流營，以及大專青年北京文教交流參訪團\n2. 為陸生最多的大學",
      "more": ""
  },
  {
      "university": "國立台北科技大學",
      "cross_course": "Y",
      "short_term": "Y",
      "internship": "Y",
      "internalize": "N",
      "fori_student": 330,
      "local_student": 91,
      "intern_student": 2,
      "english_course": 8,
      "international_point": "1. 新南向「世界工廠」計劃：台灣與泰國學生互相到對方國家交換、實習\n2. 跨日本、中國合作專案，學生一起幫各國企業解決問題",
      "more": "移地訓練：\n北科大 台日中三地做專案"
  },
  {
      "university": "東海大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "Y",
      "internalize": "N",
      "fori_student": 284,
      "local_student": 450,
      "intern_student": 3,
      "english_course": 1,
      "international_point": "1. 台灣Ｘ義大利實習計劃，讓學生到義大利企業實習",
      "more": ""
  },
  {
      "university": "元智大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 271,
      "local_student": 660,
      "intern_student": "",
      "english_course": 2,
      "international_point": "1. 「新雙語」大學，將程式語言列為必修，全校有三分之一課程為英語課程",
      "more": ""
  },
  {
      "university": "國立中興大學",
      "cross_course": "Y",
      "short_term": "Y",
      "internship": "Y",
      "internalize": "N",
      "fori_student": 268,
      "local_student": 157,
      "intern_student": 1,
      "english_course": 5,
      "international_point": "1. 全國唯一的獸醫跨國雙聯學位：美國堪薩斯州立大學\n2. 2016首創三聯學程，與德國、墨西哥合作成立全英語「全球事務研究跨洲碩士學位學程」，讓學生選擇到海外企業實習。\n3. 全英語國際農業碩士學位學程、國際農企業學士學位學程\n4. 與泰國朱拉隆功大學「台灣有機農業課程」合作，學生互相到對方國家進行農業實務訓練",
      "more": ""
  },
  {
      "university": "屏東科技大學",
      "cross_course": "Y",
      "short_term": "N",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 263,
      "local_student": 117,
      "intern_student": 11,
      "english_course": 7,
      "international_point": "1. 全球永續農業學程",
      "more": ""
  },
  {
      "university": "東華大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 260,
      "local_student": 68,
      "intern_student": "",
      "english_course": 5,
      "international_point": "1. 無邊界計劃：東華寰宇書院結合國際學生與花蓮女中學生，投入鄉村服務學習",
      "more": ""
  },
  {
      "university": "南台科技大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "Y",
      "internalize": "N",
      "fori_student": 232,
      "local_student": 95,
      "intern_student": 8,
      "english_course": 10,
      "international_point": "1. 送學生到日本大廠實習",
      "more": "國際實習：南台科大SEGA實習"
  },
  {
      "university": "輔仁大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "N",
      "fori_student": 223,
      "local_student": 402,
      "intern_student": 1,
      "english_course": 2,
      "international_point": "1.提供獎學金，輔大織品系站上倫敦時裝週",
      "more": "國際伸展台：輔大織品系前進倫敦時裝週"
  },
  {
      "university": "中山大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "Y",
      "internalize": "N",
      "fori_student": 212,
      "local_student": 261,
      "intern_student": 2,
      "english_course": 6,
      "international_point": "1.「新南向學海築夢」：提供學生出國實習\n2. 中山EMBA每年皆會提供國內外知名企業參訪機會，範圍遍及美國、德國、日本、大陸、香港及越南等地\n3. 教授也帶領專業領域國際生與本地生走進在地企業提供「企業診斷與諮詢」\n4. 國際產學聯盟\n5. 中山大學2017推出「3+1+3」7年計畫，包括「學士班3年、碩士班1年、博士班3年」，並提供補助到國外大學做博士後研究",
      "more": ""
  },
  {
      "university": "台北醫學大學",
      "cross_course": "Y",
      "short_term": "N",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 212,
      "local_student": 165,
      "intern_student": 2,
      "english_course": 1,
      "international_point": "1. 提供獎學金讓醫學系學生出國實習\n2. 醫學科技學院轉譯醫學博士學位學程，選送學生至美國的約翰．霍普金斯大學及芝加哥大學進行2年期海外研修\n3. 國際盟校開設共授課程，公衛學院與美國奧勒岡州立大學，以跨國視訊進行專題討論；並將與國外學校合作開設領導與專業遠距課程",
      "more": ""
  },
  {
      "university": "世新大學",
      "cross_course": "Y",
      "short_term": "Y",
      "internship": "N",
      "internalize": "N",
      "fori_student": 192,
      "local_student": 91,
      "intern_student": "",
      "english_course": 1,
      "international_point": "1. 兩岸四地五校暑期聯合大學：和同濟大學、香港理工大學與逢甲大學跨校開課，每年課程主題不同，例如2017年就以「人文實踐與在地創新」為主題",
      "more": ""
  },
  {
      "university": "靜宜大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "N",
      "fori_student": 162,
      "local_student": 379,
      "intern_student": 4,
      "english_course": 1,
      "international_point": "1.有交換和雙聯學制可申請\n2. 105年教育部「學海飛颺」及「學海惜珠」計畫補助出國研修金額全國第一\n3. 「411遊留學計畫」：鼓勵學生於四年修課期間，至少出國遊學一次、留學一次",
      "more": ""
  },
  {
      "university": "亞洲大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 159,
      "local_student": 30,
      "intern_student": 6,
      "english_course": 15,
      "international_point": "1. 國際學生以蒙古學生最多，並與蒙古的大學簽訂雙聯學位\n2. 亞洲大學休憩系暑假展開海外移地教學\n3. 「318」計畫：中、英文及程式語言「3」種語言優勢，並透過「雙聯學位」、留學、交換、海外參訪與實習、國際競賽、論文研討會、國際志工等方式補助學生大學四年至少出國一次",
      "more": ""
  },
  {
      "university": "實踐大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 111,
      "local_student": 541,
      "intern_student": 6,
      "english_course": 1,
      "international_point": "1. 「虛擬國際學院」，採用全英語教學，重視問題導向、資源整合、團隊合作，讓學生做中學，完成專案研究",
      "more": ""
  },
  {
      "university": "文藻外語大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 96,
      "local_student": 313,
      "intern_student": 19,
      "english_course": "",
      "international_point": "1. 外籍老師最多\n2. 和法國合作輸出華語教育\n3. 「文藻桌」：派遣學生前往海外姐妹校實習，擔任華語教學、英語輔導或行政助理等\n4. 受美國國務院委託，協助培養華語人才",
      "more": ""
  },
  {
      "university": "國立台灣海洋大學",
      "cross_course": "Y",
      "short_term": "N",
      "internship": "N",
      "internalize": "N",
      "fori_student": 95,
      "local_student": 327,
      "intern_student": 6,
      "english_course": 2,
      "international_point": "1. 與法國里爾科技大學簽訂學術交流雙聯學制合作計劃",
      "more": ""
  },
  {
      "university": "吳鳳科技大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 92,
      "local_student": 2,
      "intern_student": "",
      "english_course": "",
      "international_point": "1. 和德國西門子公司合作配合課程產學合作\n2. 跟遠東機械合作印度產學專班",
      "more": ""
  },
  {
      "university": "高雄餐旅大學",
      "cross_course": "Y",
      "short_term": "Y",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 86,
      "local_student": 150,
      "intern_student": 3,
      "english_course": 2,
      "international_point": "1. 與英國、日本、美國、澳洲簽訂雙聯學制\n2. 全英語國際觀光學士學位學程、國際廚藝學士學位學程\n3. 全英文授課之觀光管理博士課程，邀請國外學者校內教授與合開博士班課程\n4. 日本、新加坡、澳門等知名酒店實習",
      "more": ""
  },
  {
      "university": "東吳大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "N",
      "fori_student": 78,
      "local_student": 447,
      "intern_student": "",
      "english_course": "",
      "international_point": "1.與蘇州大學簽訂「人文社會科學研究協作倡議書」",
      "more": ""
  },
  {
      "university": "雲林科技大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "Y",
      "internalize": "N",
      "fori_student": 76,
      "local_student": 98,
      "intern_student": 1,
      "english_course": 3,
      "international_point": "1. 教育部「學海A+」蹲點計劃：送遊戲設計系學生到日本遊戲大廠實習",
      "more": ""
  },
  {
      "university": "國立暨南國際大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "Y",
      "internalize": "Y",
      "fori_student": 62,
      "local_student": 95,
      "intern_student": 8,
      "english_course": "",
      "international_point": "1. 「新南向學海築夢」：提供學生出國實習\n2. 結合東南亞研究特色，首創全國唯一東南亞學系",
      "more": ""
  },
  {
      "university": "國立台北大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 47,
      "local_student": 504,
      "intern_student": "",
      "english_course": 2,
      "international_point": "1. 全球經濟分析與領導人才英語學士學分學程\n2. 和香港科大合作Global Citizenship課程，讓兩邊學生到各自城市交流，探討永續城市譬如光害、剩食等議題，2017年亞利桑那州州立大學學生也加入",
      "more": ""
  },
  {
      "university": "長榮大學",
      "cross_course": "N",
      "short_term": "N",
      "internship": "N",
      "internalize": "Y",
      "fori_student": 45,
      "local_student": 203,
      "intern_student": 2,
      "english_course": 1,
      "international_point": "1. 國際珍古德根與芽生態教育中心，推動生態教育，關注永續環境",
      "more": ""
  },
  {
      "university": "高雄第一科技大學",
      "cross_course": "N",
      "short_term": "Y",
      "internship": "N",
      "internalize": "N",
      "fori_student": 42,
      "local_student": 99,
      "intern_student": 2,
      "english_course": "",
      "international_point": "1. 與姐妹校上奧地利邦專業高等學院舉辦研習營，和他同國學生共同探討跨國際、跨文化的社會工作及社會福利等議題\n2. 與印尼學校合作，讓學生赴印尼研修",
      "more": ""
  }
]